version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    expose:
      - "8000"
    networks:
      [app]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
    expose:
      - "3000"
    depends_on:
      [backend]
    networks:
      [app]

networks:
  app:
    driver: bridge