services:
  backend:
    build:
      context: ./backend_ml
      dockerfile: Dockerfile
    volumes:
      - ./backend_ml/models:/app/models:ro
    networks:
      - app

  lightcurve:
    build:
      context: ./lightcurve
      dockerfile: Dockerfile
    volumes:
      - ./lightcurve/models:/app/models:ro
      - ./lightcurve/data:/app/data:ro
      - ./lightcurve/pixelfiles:/app/pixelfiles:ro
    networks:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: "production"
      BACKEND_URL: "http://backend:8000"
      LIGHTCURVE_API_URL: "http://lightcurve:9000"
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
      PORT: "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - backend
      - lightcurve
    networks:
      - app

# Internal bridge network for service communication
networks:
  app:
    driver: bridge
# Usage:
# - Browser access: http://localhost:3000 (frontend only)
# - Backend is internal: Next.js server calls backend via BACKEND_URL
# - To expose backend in dev, add 'ports: ["8000:8000"]' to backend service
