services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
    networks:
      - app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "${PORT:-3000}:3000"
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_API_URL: "http://backend:8000"
      PORT: "3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - backend
    networks:
      - app

# Internal bridge network for service communication
networks:
  app:
    driver: bridge
# Usage:
# - Browser access: http://localhost:3000 (frontend only)
# - Backend is internal: Next.js server calls backend via BACKEND_URL
# - To expose backend in dev, add 'ports: ["8000:8000"]' to backend service
