import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedOut,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeProvider as NextThemesProvider } from 'next-themes'
import Sidebar from '@/components/Sidebar'
import { cn } from '@/lib/utils'
import { Toaster } from 'sonner'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={cn(`${geistSans.variable} ${geistMono.variable} antialiased bg-secondary`)}>
        <ClerkProvider>
          {/* NextThemesProvider must be inside <body> */}
          <NextThemesProvider
            attribute="class"
            defaultTheme="system"
            enableSystem={true}
            disableTransitionOnChange
          >
            <Navbar />
            <div className='hidden md:flex mt-16 w-20 flex-col fixed inset-y-0'>
              <Sidebar />
            </div>

            <header className="flex justify-end items-center p-0 gap-4 pt-3">
              <SignedOut>
                <SignInButton />
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
            </header>

            <main className="pt-16">
              {children}
              <Toaster />
            </main>
          </NextThemesProvider>
        </ClerkProvider>
      </body>
    </html>
  )
}
